SELECT [b].[id]
      ,[u].[user_name] AS [UserId]
      ,[b].[budget_number] AS [BudgetNumber]
      ,[b].[customer_name] AS [CustomerName]
      ,[b].[customer_address] AS [CustomerAddress]
      ,TRIM([b].[observation]) AS [Observation]
      ,[b].[dateTime]
      ,[b].[total]
      ,[b].[payment]
      ,[b].[is_inactive] AS [IsInactive]
      ,[b].[company_id] AS [CompanyId]
	  ,[bd].[id]
      ,[bd].[budget_id] AS [BudgetId]
      ,[bd].[product_id] AS [ProductId]
      ,[bd].[product_name] AS [ProductName]
      ,[bd].[product_code] AS [ProductCode]
      ,[bd].[quantity]
      ,[bd].[price]
  FROM [budget] [b]
  INNER JOIN 
  [budget_detail] [bd] ON [b].[id] = [bd].[budget_id]
  LEFT JOIN [user] [u] ON [u].[id] = [b].[user_id]
  WHERE [b].[id] = @id
  AND [b].[company_id] = @companyid;