SELECT [p].[id]
      ,[p].[description] AS [description]
      ,[p].[code] AS [code]
      ,[c].[description] AS [categoryName]
      ,[b].[description] AS [brandName]
      ,[p].[quantity] AS [quantity]
      ,[p].[purchase_price] AS [purchasePrice]
      ,[p].[sale_price] AS [salePrice]
      ,[p].[sale_percentage] AS [salePercentage]
      ,[p].[card_sale_price] AS [cardSalePrice]
      ,[p].[card_sale_percentage] AS [cardSalePercentage]
      ,[p].[cash_sale_price] AS [cashSalePrice]
      ,[p].[cash_sale_percentage] AS [cashSalePercentage]
      ,[p].[point_order] AS [pointOrder]
      ,[p].[observation] AS [observation]
      ,[e].[name] AS [supplierName]
      ,[p].[bar_code] AS [barCode]
      ,[p].[is_deleted] AS [isDeleted]
  FROM [product] [p]
  LEFT JOIN [category] [c]
  ON [c].[id] = [p].[category_id]

  LEFT JOIN [entity][e]
  ON [e].[id] = [p].[supplier_id]

  LEFT JOIN [brand] [b]
  ON [b].[id] = [p].[brand_id]

  WHERE [p].[id] = @productid;