//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ordbox.Services.Scripts {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ordbox.Services.Scripts.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [b].[id]
        ///      ,[b].[description]
        ///  FROM [brand] [b]
        ///  WHERE [b].[id] = @id;.
        /// </summary>
        internal static string GetBrandById {
            get {
                return ResourceManager.GetString("GetBrandById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [b].[id] AS [value]
        ///      ,[b].[description] AS [label]
        ///  FROM [brand] [b]
        ///  INNER JOIN [product] [p]
        ///  ON [p].[brand_id] = [b].[id]
        ///  WHERE [p].[id] = @productid;.
        /// </summary>
        internal static string GetBrandByIdForList {
            get {
                return ResourceManager.GetString("GetBrandByIdForList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [b].[id]
        ///      ,[u].[user_name] AS [UserId]
        ///      ,[b].[budget_number] AS [BudgetNumber]
        ///      ,[b].[customer_name] AS [CustomerName]
        ///      ,[b].[customer_address] AS [CustomerAddress]
        ///      ,TRIM([b].[observation]) AS [Observation]
        ///      ,[b].[dateTime]
        ///      ,[b].[total]
        ///      ,[b].[payment]
        ///      ,[b].[is_inactive] AS [IsInactive]
        ///	  ,[bd].[id]
        ///      ,[bd].[budget_id] AS [BudgetId]
        ///      ,[bd].[product_id] AS [ProductId]
        ///      ,[bd].[product_name] AS [ProductName]
        ///      ,[bd].[produc [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GetBudgetById {
            get {
                return ResourceManager.GetString("GetBudgetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [c].[id]
        ///      ,[c].[description]
        ///  FROM [category] [c]
        ///  WHERE [c].[id] = @id;.
        /// </summary>
        internal static string GetCategoryById {
            get {
                return ResourceManager.GetString("GetCategoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [c].[id] AS [value]
        ///      ,[c].[description] AS [label]
        ///  FROM [category] [c]
        ///  INNER JOIN [product] [p]
        ///  ON [p].[category_id] = [c].[id]
        ///  WHERE [p].[id] = @productid;.
        /// </summary>
        internal static string GetCategoryByIdForList {
            get {
                return ResourceManager.GetString("GetCategoryByIdForList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [p].[id]
        ///      ,[p].[description] AS [description]
        ///      ,[p].[code] AS [code]
        ///      ,[c].[description] AS [categoryName]
        ///      ,[b].[description] AS [brandName]
        ///      ,[p].[quantity] AS [quantity]
        ///      ,[p].[purchase_price] AS [purchasePrice]
        ///      ,[p].[sale_price] AS [salePrice]
        ///      ,[p].[sale_percentage] AS [salePercentage]
        ///      ,[p].[card_sale_price] AS [cardSalePrice]
        ///      ,[p].[card_sale_percentage] AS [cardSalePercentage]
        ///      ,[p].[cash_sale_price] AS [cashSalePrice]
        ///       [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GetCompleteProductById {
            get {
                return ResourceManager.GetString("GetCompleteProductById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   SELECT (1) FROM [brand] B
        ///  INNER JOIN [product] P
        ///  ON P.brand_id = B.id
        ///  WHERE B.id = @brandid
        ///  AND P.[is_deleted] = 0.
        /// </summary>
        internal static string GetCountBrandById {
            get {
                return ResourceManager.GetString("GetCountBrandById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   SELECT (1) FROM [category] C
        ///  INNER JOIN [product] P
        ///  ON P.[category_id] = C.id
        ///  WHERE C.id = @categoryid
        ///  AND P.[is_deleted] = 0.
        /// </summary>
        internal static string GetCountCategoryById {
            get {
                return ResourceManager.GetString("GetCountCategoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [id]
        ///      ,[credit_id] AS [CreditId]
        ///      ,[request]
        ///      ,[response]
        ///      ,[endpoint]
        ///      ,[success]
        ///      ,[created_on] AS [createdOn]
        ///  FROM [integration_log_credit]
        ///  WHERE [credit_id] = @id.
        /// </summary>
        internal static string GetIntegrationLogCreditById {
            get {
                return ResourceManager.GetString("GetIntegrationLogCreditById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [id]
        ///      ,[debit_id] AS [DebitId]
        ///      ,[request]
        ///      ,[response]
        ///      ,[endpoint]
        ///      ,[success]
        ///      ,[created_on] AS [createdOn]
        ///  FROM [integration_log_debit]
        ///  WHERE [debit_id] = @id.
        /// </summary>
        internal static string GetIntegrationLogDebititById {
            get {
                return ResourceManager.GetString("GetIntegrationLogDebititById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [id]
        ///      ,[invoice_id] AS [invoiceId]
        ///      ,[request]
        ///      ,[response]
        ///      ,[endpoint]
        ///      ,[success]
        ///      ,[created_on] AS [createdOn]
        ///  FROM [integration_log_invoice]
        ///  WHERE [invoice_id] = @invoiceid.
        /// </summary>
        internal static string GetIntegrationLogInvoiceByInvoiceId {
            get {
                return ResourceManager.GetString("GetIntegrationLogInvoiceByInvoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @DesiredOffSet VARCHAR(6) = &apos;+00:00&apos;;
        ///
        ///SELECT [i].[id]
        ///      ,[i].[invoice_number] AS [InvoiceNumber]
        ///      ,[i].[customer_name] AS [CustomerName]
        ///      ,[i].[customer_cuit] AS [CustomerCuit]
        ///      ,[i].[dateTime]
        ///      ,[i].[total]
        ///      ,[i].[iva_total] AS [IvaTotal]
        ///      ,[i].[type]
        ///	  ,[id].[id]
        ///	  ,[id].[invoice_id] AS [InvocieId]
        ///      ,[id].[product_id] AS [ProductId]
        ///      ,[id].[product_code]
        ///      ,[id].[quantity]
        ///      ,[id].[price]
        ///      ,[id].[iva]
        ///      ,[id].[cae]
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GetInvoiceByDate {
            get {
                return ResourceManager.GetString("GetInvoiceByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  SELECT (1) FROM [product] P
        ///  
        ///  WHERE P.id = @productid.
        /// </summary>
        internal static string GetProductById {
            get {
                return ResourceManager.GetString("GetProductById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT	[p].[id], 
        ///		[p].[description], 
        ///		[p].[code], 
        ///		[B].[description] AS [brandName], 
        ///		[p].[quantity],
        ///		[p].[purchase_price],
        ///		CONVERT (DECIMAL(18,2), ([p].[quantity] * [p].[purchase_price])) AS [subTotal]
        ///
        ///FROM [product] [p] 
        ///
        ///JOIN [brand] [B]
        ///ON [B].[id] = [p].[brand_id]
        ///
        ///WHERE [quantity] &gt; 0 AND [is_deleted] = 0
        ///ORDER BY [p].[description].
        /// </summary>
        internal static string GetProductReport {
            get {
                return ResourceManager.GetString("GetProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WITH FilteredReceipts AS (
        ///    SELECT 
        ///        r.Id,
        ///        r.[receipt_number] AS ReceiptNumber,
        ///        r.[dateTime],
        ///        r.[supplier_cuit] AS SupplierCuit,
        ///        r.[supplier_name] AS SupplierName,
        ///		u.[first_name] AS CreatedBy,
        ///		r.[total],
        ///		r.[type]
        ///    FROM [receipt] [r]
        ///    INNER JOIN [user] u ON [r].[user_id] = u.Id
        ///    INNER JOIN [company] c ON u.[company_id] = c.Id
        ///    WHERE c.Id = @companyid
        ///      AND r.is_inactive = 0
        ///      AND (@cuit IS NULL OR r.[supplier_cuit] LIKE &apos;%&apos; +  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GetReceiptList {
            get {
                return ResourceManager.GetString("GetReceiptList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WITH FilteredReceipts AS (
        ///    SELECT 
        ///        r.Id
        ///    FROM [receipt] [r]
        ///    INNER JOIN [user] u ON [r].[user_id] = u.Id
        ///    INNER JOIN [company] c ON u.[company_id] = c.Id
        ///    WHERE c.Id = @companyid
        ///      AND r.is_inactive = 0
        ///      AND (@cuit IS NULL OR r.[supplier_cuit] LIKE &apos;%&apos; + @cuit + &apos;%&apos;)
        ///      AND (@number IS NULL OR r.[receipt_number] = @number)
        ///      AND (@date IS NULL OR CONVERT(VARCHAR(10), r.DateTime, 120) LIKE &apos;%&apos; + @date + &apos;%&apos;)
        ///      AND (@customername IS NULL OR LOWER(r.[suppl [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GetReceiptListCount {
            get {
                return ResourceManager.GetString("GetReceiptListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [s].[id] AS [value]
        ///      ,[s].[name] AS [label]
        ///  FROM [entity] [s]
        ///  INNER JOIN [product] [p]
        ///  ON [p].[supplier_id] = [s].[id]
        ///  WHERE [p].[id] = @productid;.
        /// </summary>
        internal static string GetSupplierByIdForList {
            get {
                return ResourceManager.GetString("GetSupplierByIdForList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT TOP (1) [id]
        ///  FROM [entity] WHERE LOWER([name]) = &apos;admin&apos;.
        /// </summary>
        internal static string GetUserAdminId {
            get {
                return ResourceManager.GetString("GetUserAdminId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE [product] SET quantity = quantity + @recievedquantity WHERE Id = @productid.
        /// </summary>
        internal static string UpdateProductStockById {
            get {
                return ResourceManager.GetString("UpdateProductStockById", resourceCulture);
            }
        }
    }
}
